### ISSUE TITLE
Use dedicated SLABs

### ISSUE THREAD

**Issue by l0kod** [landlock-lsm/linux#19]
Using a [`kmem_cache`](https://docs.kernel.org/core-api/mm-api.html) per Landlock's kernel type could improve performance, and it would also be useful to get some metrics via `/proc/slabinfo`.

One SLAB per:
* `struct landlock_object`
* `struct landlock_rule`
* `struct landlock_ruleset`
* `struct landlock_hierarchy`

**Comment by ayush-0110** [comment]
Hi, I am Ayush, an outreachy applicant. I have worked on several patches and got them reviewed as mentioned in project guidelines. I want to work on this issue. Can you please assign it to me and help me get started on the same?
@l0kod @AlisonSchofield

**Comment by l0kod** [comment]
I'm assigning this issue to you. Please regularly update it with your progress. This doesn't need to be long but just enough to make sure you are not blocked.

**Comment by ayush-0110** [comment]
Thanks a lot @l0kod . Will definitely keep updating progress and seek your guidance if anywhere I feel stuck.

**Comment by ayush-0110** [comment]
Hello @l0kod . I have gone through the lsm_file_cache code for reference and tried to use kmem_cache_zalloc( ) for struct landlock_object. Let me share the steps taken, kindly correct me wherever I am wrong:
1. created a struct of type kmem_cache to create cache.
2. created one initialization function to create cache to allocate memory from.
3. replaced zalloc calls with kmem_cache_zalloc( ).

the problem I am facing is: I am not getting where to call the initialisation function to ensure cache is created only once. could you help me please? @l0kod  @AlisonSchofield

**Comment by ayush-0110** [comment]
Okay. Thanks @l0kod . I am sending the changes for your review. Kindly look into them and instruct me further. Thanks.

**Comment by l0kod** [comment]
For reference: [the related patch](https://lore.kernel.org/all/ZgSrBVidW1U6yP+h@ayush-HP-Pavilion-Gaming-Laptop-15-ec0xxx/).

**Comment by ayush-0110** [comment]
Hello @l0kod. 
I was trying to work on the suggestion of Paul and I am facing some problem regarding replacing kzalloc with
kmem_cache_zalloc calls when using KMEM macro from include/linux/slab.h because for
kmem_cache_zalloc I will be needing a cache pointer, but KMEM macro
doesn't return or allocate any such pointer. So is there any way to do this using macro or do i have to avoid using that macro for this case and use all methods regarding kmem as defined in the linux memory management API doc?

**Comment by ayush-0110** [comment]
Hello @l0kod . I sent a V2 of the patch. Could you please look into it and suggest me if any changes have to be done? Thanks

**Comment by ayush-0110** [comment]
Hello @l0kod @AlisonSchofield. I have created a complete patch aimed at solving this issue where I have used kmem to replace the kzalloc calls with kmem_cache_zalloc and also have metrics using /proc/slabinfo. Kindly look into it. Thanks
Patch: https://lore.kernel.org/linux-security-module/ZgsV5RuwsiM3WwXG@ayush-HP-Pavilion-Gaming-Laptop-15-ec0xxx/T/#u

**Comment by ayush-0110** [comment]
Hello @l0kod @AlisonSchofield. Kindly look into the patch I created as today is the last date for submitting our final application.

**Comment by l0kod** [comment]
> Hello @l0kod @AlisonSchofield. Kindly look into the patch I created as today is the last date for submitting our final application.

You can use the link to the latest patch as contribution. I'll review it shortly.

**Comment by ayush-0110** [comment]
Ok @l0kod . Thanks. Now I wish to change the calls for struct landlock_ruleset as well and as you mentioned, i have to use kmem_buckets_alloc(). Can you guide me about how to proceed with it?

**Comment by l0kod** [comment]
It's too soon to work on `kmem_buckets_alloc()` because of the [ongoing discussion](https://lore.kernel.org/all/20240305100933.it.923-kees@kernel.org/). We'll see what happen.

As suggested in the mailing list, [some metrics](https://github.com/landlock-lsm/linux/issues/24) would be useful to know the impact of `kmem_cache`.

**Comment by ayush-0110** [comment]
Hello @l0kod. In my recent patch, I included some metrics from /proc/slabinfo, as that was mentioned in the issue. Any other metrics also needed for the same??

**Comment by l0kod** [comment]
> Hello @l0kod. In my recent patch, I included some metrics from /proc/slabinfo, as that was mentioned in the issue. Any other metrics also needed for the same??

By metric I mean to measure the [performance impact of such change](https://lore.kernel.org/r/20240403.Yiep0aem7wu5@digikod.net). This should help: #24

**Comment by l0kod** [comment]
I guess @ayush-0110 is not working on this task anymore. Let's close this task until we get the benchmark tools, see #24 and upstream comments.
