### ISSUE TITLE
Use the kref API

### ISSUE THREAD

**Issue by l0kod** [landlock-lsm/linux#20]
Landlock currently uses `refcount_t` types, but it would be better to use [struct kref](https://docs.kernel.org/core-api/kref.html) and the related helpers instead.

**Comment by Madhupatel08** [comment]
Hi @l0kod, 
can you assign this task to me, I'm working on it, and will raise a PR by tomorrow

**Comment by l0kod** [comment]
Hi @Madhupatel08! Looking at the consequence of using `kref` in the current code, I'm starting to think it may not be a good idea because it could increase code complexity for not much benefit. However, you can still send a patch with this change and we'll discuss on the mailing list with other reviewers looking at concret code. Anyway, it would still be a good first start if this is for Outreachy.

FYI, the Linux kernel doesn't work with PRs but patches sent by emails as explained in the documentation.
