### ISSUE TITLE
Clone ruleset

### ISSUE THREAD

**Issue by l0kod** [landlock-lsm/linux#25]
When building several similar sandboxes, it would be convenient to be able to duplicate a ruleset instead of creating it again. Duplicating the ruleset's file descriptor works but we get just get another reference to the same ruleset. Cloning a ruleset would enable us to factor out the common properties of rulesets or pass it to another process (without the risk that this ruleset get more rules).

Because the `landlock_add_rule()`'s goal is to modify a ruleset, we could add a new `LANDLOCK_ADD_RULE_CLONE` flag to first copy the ruleset (if there are more than one reference to it) and then add the new rule, if any.

This interface could also be used to set the ruleset read-only with another flag (e.g. `LANDLOCK_ADD_RULE_SEAL`).

About naming, here are some proposals: `clone` (close to the `FICLONE` semantic), `copy`, or `duplicate` (close to the `dup()` syscall)?

Cc @nbouchinet-anssi

**Comment by nbouchinet-anssi** [comment]
I'll work on it, can you assign me to the issue ?

**Comment by l0kod** [comment]
Similar need: landlock-lsm/rust-landlock#38

**Comment by nbouchinet-anssi** [comment]
The ability to set a ruleset in read-only would independently be great.

**Comment by nbouchinet-anssi** [comment]
I've opened another issue about rule deny listing, I'll will split the read-only ruleset in it own issue, I think you can close this one if your ok with it.
